<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
		<OutputType>WinExe</OutputType>
		<RootNamespace>Blue_Sky</RootNamespace>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWPF>true</UseWPF>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<ApplicationIcon>bluesky.ico</ApplicationIcon>
		<SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DebugType>none</DebugType>
	</PropertyGroup>
	<ItemGroup>
		<Resource Include="bluesky.ico" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<RuntimeHostConfigurationOption Include="Switch.System.Windows.Appearance.DisableFluentThemeWindowBackdrop" Value="true" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="Properties\Settings.Designer.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Settings.settings</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>
</Project>